version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongosh
      MONGO_INITDB_ROOT_PASSWORD: "1111"
    volumes:
      - mongodb:/data/db
    networks:
      - app

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - app

  budget_service:
    container_name: budget_service1
    build: .
    ports:
      - "8082:8082"
    networks:
      - app
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env

networks:
  app:
    external: true

volumes:
  mongodb:
  redis:
