# services:
#   rabbitmq:
#     image: rabbitmq:management
#     container_name: rabbitmq
#     ports:
#       - "5673:5672" 
#       - "15673:15672"  
#     environment:
#       RABBITMQ_DEFAULT_USER: user
#       RABBITMQ_DEFAULT_PASS: 1111
#     networks:
#       - app

#   api-service:
#     container_name: api-gateway
#     build: .
#     depends_on:
#       - rabbitmq
#     ports:
#       - "50053:50053"
#     networks:
#      - app

# networks:
#   app:
#     external: true

# volumes:
#   db:
#   rabbitmq_data:



version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5673:5672"    
      - "15673:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 1111
    networks:
      - app
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api-service:
    container_name: api-gateway
    build: .
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"  # Ensure this port is available and not conflicting
    networks:
     - app

networks:
  app:
    external: true

volumes:
  rabbitmq_data:
