// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: goal.proto

package budgeting_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GoalServiceClient is the client API for GoalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoalServiceClient interface {
	CreateGoal(ctx context.Context, in *GoalRequest, opts ...grpc.CallOption) (*Goal, error)
	UpdateGoal(ctx context.Context, in *Goal, opts ...grpc.CallOption) (*Goal, error)
	GetGoal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Goal, error)
	GetListGoals(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*Goals, error)
	DeleteGoal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetGoalReportProgress(ctx context.Context, in *GoalProgressRequest, opts ...grpc.CallOption) (*GoalProgressResponse, error)
}

type goalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGoalServiceClient(cc grpc.ClientConnInterface) GoalServiceClient {
	return &goalServiceClient{cc}
}

func (c *goalServiceClient) CreateGoal(ctx context.Context, in *GoalRequest, opts ...grpc.CallOption) (*Goal, error) {
	out := new(Goal)
	err := c.cc.Invoke(ctx, "/GoalService/CreateGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) UpdateGoal(ctx context.Context, in *Goal, opts ...grpc.CallOption) (*Goal, error) {
	out := new(Goal)
	err := c.cc.Invoke(ctx, "/GoalService/UpdateGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetGoal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Goal, error) {
	out := new(Goal)
	err := c.cc.Invoke(ctx, "/GoalService/GetGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetListGoals(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*Goals, error) {
	out := new(Goals)
	err := c.cc.Invoke(ctx, "/GoalService/GetListGoals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) DeleteGoal(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/GoalService/DeleteGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goalServiceClient) GetGoalReportProgress(ctx context.Context, in *GoalProgressRequest, opts ...grpc.CallOption) (*GoalProgressResponse, error) {
	out := new(GoalProgressResponse)
	err := c.cc.Invoke(ctx, "/GoalService/GetGoalReportProgress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoalServiceServer is the server API for GoalService service.
// All implementations must embed UnimplementedGoalServiceServer
// for forward compatibility
type GoalServiceServer interface {
	CreateGoal(context.Context, *GoalRequest) (*Goal, error)
	UpdateGoal(context.Context, *Goal) (*Goal, error)
	GetGoal(context.Context, *PrimaryKey) (*Goal, error)
	GetListGoals(context.Context, *GetListRequest) (*Goals, error)
	DeleteGoal(context.Context, *PrimaryKey) (*emptypb.Empty, error)
	GetGoalReportProgress(context.Context, *GoalProgressRequest) (*GoalProgressResponse, error)
	mustEmbedUnimplementedGoalServiceServer()
}

// UnimplementedGoalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGoalServiceServer struct {
}

func (UnimplementedGoalServiceServer) CreateGoal(context.Context, *GoalRequest) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGoal not implemented")
}
func (UnimplementedGoalServiceServer) UpdateGoal(context.Context, *Goal) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGoal not implemented")
}
func (UnimplementedGoalServiceServer) GetGoal(context.Context, *PrimaryKey) (*Goal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoal not implemented")
}
func (UnimplementedGoalServiceServer) GetListGoals(context.Context, *GetListRequest) (*Goals, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListGoals not implemented")
}
func (UnimplementedGoalServiceServer) DeleteGoal(context.Context, *PrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGoal not implemented")
}
func (UnimplementedGoalServiceServer) GetGoalReportProgress(context.Context, *GoalProgressRequest) (*GoalProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoalReportProgress not implemented")
}
func (UnimplementedGoalServiceServer) mustEmbedUnimplementedGoalServiceServer() {}

// UnsafeGoalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoalServiceServer will
// result in compilation errors.
type UnsafeGoalServiceServer interface {
	mustEmbedUnimplementedGoalServiceServer()
}

func RegisterGoalServiceServer(s grpc.ServiceRegistrar, srv GoalServiceServer) {
	s.RegisterService(&GoalService_ServiceDesc, srv)
}

func _GoalService_CreateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).CreateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoalService/CreateGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).CreateGoal(ctx, req.(*GoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_UpdateGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Goal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).UpdateGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoalService/UpdateGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).UpdateGoal(ctx, req.(*Goal))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoalService/GetGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetGoal(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetListGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetListGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoalService/GetListGoals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetListGoals(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_DeleteGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).DeleteGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoalService/DeleteGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).DeleteGoal(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoalService_GetGoalReportProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoalProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoalServiceServer).GetGoalReportProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoalService/GetGoalReportProgress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoalServiceServer).GetGoalReportProgress(ctx, req.(*GoalProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoalService_ServiceDesc is the grpc.ServiceDesc for GoalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GoalService",
	HandlerType: (*GoalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGoal",
			Handler:    _GoalService_CreateGoal_Handler,
		},
		{
			MethodName: "UpdateGoal",
			Handler:    _GoalService_UpdateGoal_Handler,
		},
		{
			MethodName: "GetGoal",
			Handler:    _GoalService_GetGoal_Handler,
		},
		{
			MethodName: "GetListGoals",
			Handler:    _GoalService_GetListGoals_Handler,
		},
		{
			MethodName: "DeleteGoal",
			Handler:    _GoalService_DeleteGoal_Handler,
		},
		{
			MethodName: "GetGoalReportProgress",
			Handler:    _GoalService_GetGoalReportProgress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goal.proto",
}
